stbkbKlaffPruef= True
stboNachweis = 1
stboQuer = 0
stboNorm = 0
stboD = 0             
stboRB = 0          
stboKR  = 0       
stboH  = [0,0,0]     
stboRe = 0          
stbodelt2 = 0      
stbobHkrit = True       
stboeBewk= 0
stbofck   = 0         
stboalpha = 0       
stboepscy  = 0      
stboepscu   = 0       
stbon2   = 0         
stbofyk= 0          
stboftk = 0          
stboepssy = 0       
stboepssu  = 0       
stboNd  = 0           
stboMd= 0            
stboQd  = 0          
stboNk = 0         
stboMk = 0          
stboeNd = 0           
stboeNk = 0         
stboVMd = 0           
stboVMk  = 0           
stboNullSd = 0    
stboNullSk = 0     
Nd1= 0
stbobDruc = [None,False,False,False]
stbodehnkrit = [0,0,0,0]   
stbomue0Dehn = [[0,0,0,0],[0,0,0,0], [0,0,0,0] ,[0,0,0,0]]   
stbovormue0 = [0,0,0]    
stbomue0Riss = [0,0,0]   
stbogamC = [0,0]       
stbogamS= [0,0]       
stboepsSmin = [0,0,0]       
stbomue0Druc= [0,0,0]    
stbosymmue0 = 0
stboRissP1  = 0        
mimue0 = [[0,0,0,0,0],[0,0,0,0,0]]
stbobminBew = False
stboii= 0
stbZgamC = [0,0,0,0]          
stbZgamS= [0,0,0,0]          
stbZnue0  = 0         

stbZepscd= [0,0,0]            
stbZepssd= [0,0,0]          
stbZepsck= [0,0,0]         
stbZepssk= [0,0,0]   
stbZRNd  = 0            
stbZRMd  = 0             
stbZRNk  =0          
stbZRMk  =0            
stbZerfmue0= [0,0,0]    
stbZmue0= [0,0,0]      

stbZsymm = 0
stboHQ  = 0          
stboBQ  = 0              
stbZNucs= [0,0,0,0]      
stbZzi= [0,0,0,0]      
stbZerfas= 0           
stbZtau0    =0        
stbotau012 =0           
stbotau02  =0         
stbotau03   =0           
stbotau1    =0          
stbotau2      =0         
stbZminas     = 0          
stbZVRdc      = 0         
stbZVRdmax  = 0           
stbZcottheta  = 0       
stbomaxcottheta  = 0      
mue_loop = False
stbZtaucp = 0        
stbZfcvd = 0             
stbZiZ = 1
stbZ_H= [0,0,0]            
stbZeps_c= [0,0,0]          
stbZeps_s= [0,0,0]       
stbZbFehler  = False
imag = 0
tracker = []
looptracker = []
erfmue2 = [0,0,0]

stbotau012 = 0
stbotau02 = 0
stbotau03= 0
stbotau1 = 0
stbotau2 = 0