# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_widget_Dim_cross_section.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1428, 873)
        Form.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 74, 127);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:rgb(215, 215, 215)\n"
"}\n"
"\n"
"QCheckBox{\n"
"background-color:rgb(215, 215, 215)\n"
"}\n"
"\n"
"\n"
"QTableWidget{\n"
"background-color:rgb(215, 215, 215)\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setBaseSize(QtCore.QSize(0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("QGroupBox{\n"
"background-color: rgb(251, 185, 0);\n"
"}\n"
"")
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(5, 5, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(5, 5, 0, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 1, 5, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(80)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 1, 6, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_5, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(80)
        self.gridLayout_4.addWidget(self.tableWidget_3, 0, 1, 5, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_4.addWidget(self.comboBox_4, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(251, 185, 0);\n"
"}")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 0, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(80)
        self.horizontalLayout_2.addWidget(self.tableWidget_4)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget_11 = QtWidgets.QTableWidget(self.groupBox_9)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(0)
        self.tableWidget_11.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_11, 0, 0, 1, 1)
        self.tableWidget_13 = QtWidgets.QTableWidget(self.groupBox_9)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.setColumnCount(0)
        self.tableWidget_13.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_13, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setContentsMargins(5, 5, -1, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setStyleSheet("background-color: rgb(242, 255, 116);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_6.addWidget(self.lineEdit_2, 1, 5, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 4, 1, 1)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidget_5.setStyleSheet("")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(60)
        self.gridLayout_6.addWidget(self.tableWidget_5, 2, 0, 1, 3)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidget_6.setStyleSheet("")
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(60)
        self.gridLayout_6.addWidget(self.tableWidget_6, 2, 4, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setStyleSheet("background-color: rgb(242, 255, 116);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_6.addWidget(self.lineEdit, 1, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(251, 185, 0);\n"
"}")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setContentsMargins(5, 5, 0, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableWidget_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.tableWidget_7.horizontalHeader().setDefaultSectionSize(80)
        self.horizontalLayout_3.addWidget(self.tableWidget_7)
        self.widget_5 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_5.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tableWidget_12 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(0)
        self.tableWidget_12.setRowCount(0)
        self.gridLayout_12.addWidget(self.tableWidget_12, 0, 0, 1, 1)
        self.tableWidget_14 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_14.setObjectName("tableWidget_14")
        self.tableWidget_14.setColumnCount(0)
        self.tableWidget_14.setRowCount(0)
        self.gridLayout_12.addWidget(self.tableWidget_14, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setContentsMargins(5, 5, 0, 5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 7, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 4, 1, 2)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox_8)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidget_8, 0, 0, 1, 1)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidget_9, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(0)
        self.tableWidget_10.setRowCount(0)
        self.gridLayout_10.addWidget(self.tableWidget_10, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 1, 0, 1, 11)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_4.setStyleSheet("background-color: rgb(242, 255, 116);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_8.addWidget(self.lineEdit_4, 0, 9, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_3.setStyleSheet("background-color: rgb(242, 255, 116);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 0, 2, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 6, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(100, 0))
        self.toolBox.setBaseSize(QtCore.QSize(0, 0))
        self.toolBox.setStyleSheet("background-color: rgb(215, 215, 215);")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 144, 809))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 144, 809))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setContentsMargins(0, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_5.addWidget(self.checkBox_2)
        self.widget_4 = QtWidgets.QWidget(self.page_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5.addWidget(self.widget_4)
        self.toolBox.addItem(self.page_3, "")
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cross-section dimensioning"))
        self.groupBox.setTitle(_translate("Form", "Code"))
        self.comboBox.setItemText(0, _translate("Form", "DIN 1045:1988"))
        self.comboBox.setItemText(1, _translate("Form", "DIN 1045:2008"))
        self.comboBox.setItemText(2, _translate("Form", "EN 1992-1-1:2004 (Eurocode 2)"))
        self.comboBox.setItemText(3, _translate("Form", "DIN EN 1992-1-1:2004 + AX:2010 + NA:2011"))
        self.groupBox_2.setTitle(_translate("Form", "Concrete"))
        self.label.setText(_translate("Form", "Concrete grade"))
        self.groupBox_3.setTitle(_translate("Form", "Reinforcement"))
        self.label_2.setText(_translate("Form", "Steel grade"))
        self.label_4.setText(_translate("Form", "Crack width"))
        self.comboBox_5.setItemText(0, _translate("Form", "no crack"))
        self.comboBox_5.setItemText(1, _translate("Form", "0.4 mm"))
        self.comboBox_5.setItemText(2, _translate("Form", "0.3 mm"))
        self.comboBox_5.setItemText(3, _translate("Form", "0.2 mm"))
        self.checkBox.setText(_translate("Form", "min. reinf.?"))
        self.groupBox_4.setTitle(_translate("Form", "PSF"))
        self.label_3.setText(_translate("Form", "Design situation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Materials and PSF"))
        self.groupBox_5.setTitle(_translate("Form", "Cross-section"))
        self.groupBox_9.setTitle(_translate("Form", "Internal forces and required reinforcement"))
        self.groupBox_6.setTitle(_translate("Form", "Given reinforcement"))
        self.lineEdit_2.setText(_translate("Form", "10, 12, 16, 20"))
        self.label_5.setText(_translate("Form", "Bar diameters for vertical reinf."))
        self.label_6.setText(_translate("Form", "Bar diameters for shear reinf."))
        self.lineEdit.setText(_translate("Form", "25, 32, 40, D25, D32, D40"))
        self.pushButton.setText(_translate("Form", "Print report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Circular"))
        self.groupBox_7.setTitle(_translate("Form", "Cross-section"))
        self.groupBox_10.setTitle(_translate("Form", "Internal forces and required reinforcement"))
        self.groupBox_8.setTitle(_translate("Form", "Given reinforcement"))
        self.label_8.setText(_translate("Form", "Bar diameters for shear reinf."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Vertical reinforcement"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "Horizontal reinforcement"))
        self.lineEdit_4.setText(_translate("Form", "10, 12, 16, 20"))
        self.label_7.setText(_translate("Form", "Bar diameters for vertical reinf."))
        self.lineEdit_3.setText(_translate("Form", "25, 32, 40, D25, D32, D40"))
        self.label_9.setToolTip(_translate("Form", "<html><head/><body><p>Embraces of shear reinforcement drawing format</p><p>- single number means 1 leg of shear reinforcement being placed at the assigned bar number.</p><p>- \'no_start no_end\' means that shear reinforcement loop (2 legs) starts at no_start and ends at no_end, e. g. \'1 8\'.</p><p>- multiple legs for shear reinforcement can be separated by a semicolon, e.g. \'1 9; 3 7; 5\' means 5 legs of shear bars placed along the main bars 1, 3, 5, 7, and 9.</p></body></html>"))
        self.label_9.setText(_translate("Form", "Information?"))
        self.pushButton_2.setText(_translate("Form", "Print report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Rectangular"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "Materials"))
        self.checkBox_2.setText(_translate("Form", "Rotate plot?"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "Reinforcement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

