# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_dialog_edit_soil_HSsmall.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1090, 368)
        Dialog.setStyleSheet("QWidget{background-color: rgb(0, 74, 127);}\n"
"\n"
"QTableWidget{background-color: rgb(255, 255, 255);}\n"
"\n"
"QCheckBox{background-color: rgb(255, 255, 255);}\n"
"\n"
"QWidget#widget{background-color: rgb(255, 255, 255);}\n"
"\n"
"QGroupBox{background-color: rgb(251, 185, 0);}\n"
"\n"
"QPushButton{background-color: rgb(205, 205, 205);}\n"
"\n"
"QLineEdit{background-color:rgb(255, 255, 255);}\n"
"\n"
"QLabel{background-color:rgb(215, 215, 215);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 5, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 2, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 5, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 6, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 10, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 10, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 9, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 9, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 3, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 5, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 6, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 11, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 9, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 3, 10, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 11, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 11, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Soil properties"))
        self.label_8.setText(_translate("Dialog", "G<sub>0</sub><sup>ref</sup> [kN/m<sup>2</sup>]"))
        self.comboBox.setItemText(0, _translate("Dialog", "Cobbles"))
        self.comboBox.setItemText(1, _translate("Dialog", "Gravel, dense"))
        self.comboBox.setItemText(2, _translate("Dialog", "Gravel, medium"))
        self.comboBox.setItemText(3, _translate("Dialog", "Gravel, loose"))
        self.comboBox.setItemText(4, _translate("Dialog", "Sand, dense"))
        self.comboBox.setItemText(5, _translate("Dialog", "Sand, medium"))
        self.comboBox.setItemText(6, _translate("Dialog", "Sand, loose"))
        self.comboBox.setItemText(7, _translate("Dialog", "Silt, hard"))
        self.comboBox.setItemText(8, _translate("Dialog", "Silt, stiff"))
        self.comboBox.setItemText(9, _translate("Dialog", "Silt, firm"))
        self.comboBox.setItemText(10, _translate("Dialog", "Silt, soft"))
        self.comboBox.setItemText(11, _translate("Dialog", "Silt, very soft"))
        self.comboBox.setItemText(12, _translate("Dialog", "Clay, hard"))
        self.comboBox.setItemText(13, _translate("Dialog", "Clay, stiff"))
        self.comboBox.setItemText(14, _translate("Dialog", "Clay, firm"))
        self.comboBox.setItemText(15, _translate("Dialog", "Clay, soft"))
        self.comboBox.setItemText(16, _translate("Dialog", "Clay, very soft"))
        self.comboBox.setItemText(17, _translate("Dialog", "Fill"))
        self.label_6.setText(_translate("Dialog", "E<sub>50</sub><sup>ref</sup>/E<sub>oed</sub><sup>ref</sup>"))
        self.label_5.setText(_translate("Dialog", "we [-]"))
        self.label_7.setText(_translate("Dialog", "E<sub>ur</sub><sup>ref</sup>/E<sub>50</sub><sup>ref</sup>"))
        self.label_4.setText(_translate("Dialog", "ve [-]"))
        self.pushButton.setText(_translate("Dialog", "Load"))
        self.label.setText(_translate("Dialog", "Material name"))
        self.label_2.setText(_translate("Dialog", "E<sub>oed</sub><sup>ref</sup> [kN/m<sup>2</sup>]"))
        self.label_3.setText(_translate("Dialog", "p<sup>ref</sup> [kN/m<sup>2</sup>]"))
        self.label_9.setText(_translate("Dialog", "gamma07"))
        self.pushButton_2.setText(_translate("Dialog", "Update"))
        self.label_10.setText(_translate("Dialog", "E<sub>dyn</sub>/E<sub>sta</sub>"))
        self.checkBox.setText(_translate("Dialog", "Correlations with ve[-]"))
        self.label_11.setToolTip(_translate("Dialog", "<html><head/><body><p>The refernce oedometric stiffness modulus EoedRef is defined by <span style=\" font-style:italic;\">ve</span>, <span style=\" font-style:italic;\">we</span>, the reference pressure <span style=\" font-style:italic;\">Pref</span>, and the atmospheric pressure <span style=\" font-style:italic;\">Pat</span> by the relation <span style=\" font-style:italic;\">EoedRef = ve * Pat * (Pref/Pat)^we</span>.</p><p><span style=\" font-style:italic;\">E50ref</span>, <span style=\" font-style:italic;\">EurRef</span> will follow EoefRef by the respective ratios. <span style=\" font-style:italic;\">G0ref</span> is calculated by the relation <span style=\" font-style:italic;\">G0ref = EurRef/2.4 * Edyn/Esta</span>.</p><p>If correlation with <span style=\" font-style:italic;\">ve</span> is checked. The parameters <span style=\" font-style:italic;\">phi</span>, <span style=\" font-style:italic;\">we</span>, <span style=\" font-style:italic;\">gammaSat</span>, <span style=\" font-style:italic;\">gammUnsat</span> will follow the linear correlations with ve. At present, we test the correlations for poor-graded fine sand described in Table 1, Grundbau-Taschenbuch.</p><p>K0nc is updated following the relation<span style=\" font-style:italic;\"> K0nc = 1 - </span>sin<span style=\" font-style:italic;\">(phi)</span>.</p><p>Dilatancy <span style=\" font-style:italic;\">psi</span> is updated following the relation <span style=\" font-style:italic;\">psi = phi - 30 </span>if<span style=\" font-style:italic;\"> phi &gt; 30; </span>else<span style=\" font-style:italic;\"> psi = 0</span>.</p><p>The above relations take effects when you click on <span style=\" font-weight:600;\">Update</span>. After updating, soil parameters shown in the table are free to be modified by the user.</p></body></html>"))
        self.label_11.setText(_translate("Dialog", "Information?"))
        self.pushButton_3.setText(_translate("Dialog", "Select color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

